# Generated by Django 3.0 on 2021-04-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='car_name',
            field=models.CharField(choices=[('su', 'suziki'), ('b', 'BMW'), ('TO', 'Toyota')], default='Toyota', max_length=100),
        ),
    ]
