# Generated by Django 3.0 on 2021-04-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210426_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservice',
            name='da',
        ),
    ]
