# Generated by Django 3.0 on 2021-04-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_userservice_da'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservice',
            name='carno',
        ),
    ]
